sudo: true
language: python
dist: xenial
env:
  - DOCKER_COMPOSE_VERSION=1.24.0
python:
  - 2.7
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
before_script:
  - docker-compose up -d
script:
  - ./docker-test.sh
after_script:
  - docker-compose down
